apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubez
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-kubez
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubez
  namespace: default

---

apiVersion: v1
kind: Pod
metadata:
  name: kubez-autoscaler-controller
  namespace: default
spec:
  containers:
  - image:  jacky06/kubez-autoscaler-controller:v0.0.1
    imagePullPolicy: IfNotPresent
    name: kubez-autoscaler-controller
