apiVersion: v1
kind: ServiceAccount
metadata:
  name: pixiuautoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pixiuautoscaler
rules:
- apiGroups:
  - "*"
  resources:
  - horizontalpodautoscalers
  - deployments
  - statefulsets
  - endpoints
  - leases
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pixiuautoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pixiuautoscaler
subjects:
- kind: ServiceAccount
  name: pixiuautoscaler
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixiu-autoscaler-controller
  namespace: kube-system
  labels:
    pixiu.hpa.controller: pixiu-autoscaler-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      pixiu.hpa.controller: pixiu-autoscaler-controller
  template:
    metadata:
      labels:
        pixiu.hpa.controller: pixiu-autoscaler-controller
    spec:
      serviceAccountName: pixiuautoscaler
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: pixiu.hpa.controller
                  operator: In
                  values:
                  - pixiu-autoscaler-controller
      containers:
      - name: pixiu-autoscaler-controller
        image: jacky06/pixiu-autoscaler-controller
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 90Mi
        command: 
        - pixiu-autoscaler-controller
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 10256
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
